/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejemplo14;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author fox
 */
public class Registro extends javax.swing.JFrame {
Connection conn;
Statement t;
ResultSet r;
ConexionMySQL mic;
Alumno a;
    /**
     * Creates new form Registro
     */
    public Registro() throws SQLException {
        initComponents();
        mic=new ConexionMySQL("ejemplo14");
        mic.conectar();
        conn=mic.getConexion();
        t=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        String sql="Select * from alumnos";
        r=t.executeQuery(sql);
        r.first();
        mostrarDatos();
    }
    public void mostrarDatos() throws SQLException{
        this.jTextField1.setText(r.getString(1));
        this.jTextField2.setText(r.getString(2));
        this.jTextField3.setText(r.getString(3));
        this.jTextField4.setText(r.getString(4));
        this.jTextField5.setText(r.getString(5));
    }
    public void primero() throws SQLException{
        r.first();
        mostrarDatos();
    }
    public void ultimo() throws SQLException{
        r.last();
        mostrarDatos();
    }
    public void siguiente() throws SQLException{
        r.next();
        if(r.isAfterLast()){
            r.last();
            mostrarDatos();
        }else{
            mostrarDatos();
        }
    }
    public void anterior() throws SQLException{
        r.previous();
        if(r.isBeforeFirst()){
            r.first();
            mostrarDatos();
        }else{
            mostrarDatos();
        }
        
    }
    public void guardar(Alumno a) throws SQLException{
        t=null;
        t=conn.createStatement();
        String sql="Insert into alumnos(Matricula,Nombre,Apellido1,Apellido2,Edad)"
                +" VALUES('"+a.getMatricula()+"','"+a.getNombre()+"','"+a.getApellido1()+"','"
                +a.getApellido2()+"',"+a.getEdad()+")";
        t.executeUpdate(sql);// aquí ya se inserto el registro
        t=null;
        t=conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        String sql2="Select * from alumnos";
        r=t.executeQuery(sql2);
        r.first();
        mostrarDatos();
    }
    public void buscar(String m) throws SQLException{
        t = null;
        t = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        String sql = "SELECT * FROM alumnos where matricula = '" +m+ "'";
        r = t.executeQuery(sql);
        //Indica que el ResultSet no esta vaci
        if (r.absolute(-1)){
            r.first();
            mostrarDatos();
        }
        else{
            JOptionPane.showMessageDialog(null, "Matricula no existe");
        }
        
    }
    public void actualizar(Alumno a, String m) throws SQLException{
        t = null;
        t = conn.createStatement();
        String sql = "UPDATE alumnos SET "
           + "Nombre='" + a.getNombre() + "', "
           + "Apellido1='" + a.getApellido1() + "', "
           + "Apellido2='" + a.getApellido2() + "', "
           + "edad=" + a.getEdad() + " "
           + "WHERE matricula='" + m + "'";

        t.executeUpdate(sql);
        t = null;
        t = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        String sql2 = "Select * from alumnos";
        t.executeQuery(sql2);
        r.first();
        mostrarDatos();
    }
    public void terminar(){
        System.exit(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnprimero = new javax.swing.JButton();
        btnanterior = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();
        btnultimo = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnterminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("R E G I S T R O     D E      A L U M N O S");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setText("MATRICULA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 310, -1));

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 310, -1));

        jTextField3.setText("jTextField3");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 310, -1));

        jTextField4.setText("jTextField4");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 310, -1));

        jTextField5.setText("jTextField5");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 310, -1));

        jLabel3.setText("NOMBRE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setText("APELLIDO 1:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setText("APELLIDO 2:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel6.setText("EDAD:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 140, 180));

        jLabel8.setText("jLabel8");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 250, 120));

        btnprimero.setText("|<");
        btnprimero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprimeroMouseClicked(evt);
            }
        });
        jPanel1.add(btnprimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 70, -1));

        btnanterior.setText("<");
        btnanterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnanteriorMouseClicked(evt);
            }
        });
        jPanel1.add(btnanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 60, -1));

        btnsiguiente.setText(">");
        btnsiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsiguienteMouseClicked(evt);
            }
        });
        jPanel1.add(btnsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 50, -1));

        btnultimo.setText(">|");
        btnultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnultimoMouseClicked(evt);
            }
        });
        jPanel1.add(btnultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 60, -1));

        btnnuevo.setText("Nuevo");
        btnnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnuevoMouseClicked(evt);
            }
        });
        jPanel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 90, -1));

        btnguardar.setText("Guardar");
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnguardarMouseClicked(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 90, -1));

        btneliminar.setText("Eliminar");
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarMouseClicked(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 80, -1));

        btnactualizar.setText("Actualizar");
        btnactualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnactualizarMouseClicked(evt);
            }
        });
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 100, -1));

        btnbuscar.setText("Buscar");
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 100, -1));

        btnterminar.setText("Terminar");
        btnterminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnterminarMouseClicked(evt);
            }
        });
        jPanel1.add(btnterminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 110, -1));

        jButton1.setText("Mostrar Todo");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprimeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprimeroMouseClicked
    try {
        primero();
    } catch (SQLException ex) {
        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnprimeroMouseClicked

    private void btnanteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnanteriorMouseClicked
    try {
        anterior();
    } catch (SQLException ex) {
        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnanteriorMouseClicked

    private void btnsiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsiguienteMouseClicked
    try {
        siguiente();
    } catch (SQLException ex) {
        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnsiguienteMouseClicked

    private void btnultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnultimoMouseClicked
    try {
        ultimo();
    } catch (SQLException ex) {
        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnultimoMouseClicked

    private void btnnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoMouseClicked
        this.jTextField1.setText(null);
        this.jTextField2.setText(null);
        this.jTextField3.setText(null);
        this.jTextField4.setText(null);
        this.jTextField5.setText(null);
        this.jTextField1.requestFocus();
    }//GEN-LAST:event_btnnuevoMouseClicked

    public void eliminar(String m) throws SQLException{
        t = null;
        t = conn.createStatement();
        String sql = "DELETE from alumnos where Matricula = '" +m+ "'";
        t.executeUpdate(sql); //Aquí ya se elimino el registro 
        t = null;
        t = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        String sql2 = "Select * from alumnos";
        r = t.executeQuery(sql2);
        r.first();
        mostrarDatos();
    }
    private void btnguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseClicked
    try {
        String m,n,ap1,ap2;
        int e;
        m=this.jTextField1.getText();
        n=this.jTextField2.getText();
        ap1=this.jTextField3.getText();
        ap2=this.jTextField4.getText();
        e=Integer.parseInt(this.jTextField5.getText());
        a=new Alumno(m, n, ap1, ap2, e);
        this.guardar(a);
    } catch (SQLException ex) {
        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btnguardarMouseClicked

    private void btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseClicked
    try {
        // TODO add your handling code here:
        String m = this.jTextField1.getText();
        this.eliminar(m);
    } catch (SQLException ex) {
        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btneliminarMouseClicked

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
    try {
        // TODO add your handling code here:
        String m = JOptionPane.showInputDialog("Matricula a buscar: ");
        this.buscar(m);
    } catch (SQLException ex) {
        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnbuscarMouseClicked

    private void btnactualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnactualizarMouseClicked
    try {
        String m, n, ap1, ap2;
        int e;
        m = this.jTextField1.getText();
        n = this.jTextField2.getText();
        ap1 = this.jTextField3.getText();
        ap2 = this.jTextField4.getText();
        e = Integer.parseInt(this.jTextField5.getText());
        a = new Alumno(m, n, ap1, ap2, e);
        this.actualizar(a, m);
    } 
    catch (SQLException ex) {
        Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnactualizarMouseClicked
    
    
    private void btnterminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnterminarMouseClicked
        // TODO add your handling code here:
        btnterminar.addActionListener(e -> terminar());

    }//GEN-LAST:event_btnterminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Registro().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnprimero;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JButton btnterminar;
    private javax.swing.JButton btnultimo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
